<a href="https://colab.research.google.com/github/C0deB3ast/Data_analysis_work/blob/main/Analysis_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#Install datasets Library
# !pip install datasets

#Import Library
import pandas as pd
from datasets import load_dataset

# Loading DATA
datasets = load_dataset('lukebarousse/data_jobs')
df = datasets['train'].to_pandas()

#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

DATA ANALYSIS Start here

---



---

In [ ]:
df['salary_year_avg'].median()

115000.0

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].median() # using group by method

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [ ]:
df.groupby(['job_title_short','job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

Here's an example demonstrating how to apply multiple aggregation functions at once. We'll find the `min`, `max`, and `median` `salary_year_avg` for each `job_title_short`.

In [13]:
aggregated_salaries = df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median'])
display(aggregated_salaries)

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

You can also apply different functions to different columns, or even custom functions. For example, let's get the median salary and the count of job postings for each `job_title_short`.

In [4]:
custom_agg = df.groupby('job_title_short').agg(
    median_salary=('salary_year_avg', 'median'),
    job_post_count=('job_title_short', 'count')
)
display(custom_agg)

                           median_salary  job_post_count
job_title_short
Business Analyst                 85000.0           49063
Cloud Engineer                   90000.0           12331
Data Analyst                     90000.0          196075
Data Engineer                   125000.0          186241
Data Scientist                  127500.0          172286
Machine Learning Engineer       106415.0           14080
Senior Data Analyst             111175.0           29216
Senior Data Engineer            147500.0           44563
Senior Data Scientist           155500.0           36957
Software Engineer                99150.0           44929

**ANALYSIS EXAMPLE**

---



---

In [16]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [17]:
India = df[df['job_country'] == 'India']

In [20]:
India = India[India['salary_year_avg'].notna()]
India

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1209,Machine Learning Engineer,Computer Vision Developer (R&D),"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-02-18 13:12:30,False,False,India,year,79200.0,NaN,Bosch Group,"['python', 'opencv', 'tensorflow', 'pytorch', ...","{'libraries': ['opencv', 'tensorflow', 'pytorc..."
2022,Data Engineer,Data Engineer - SQL (Power BI),India,via Ai-Jobs.net,Full-time,False,India,2023-10-31 13:09:54,False,False,India,year,156500.0,NaN,Gartner,"['java', 't-sql', 'sql', 'azure', 'power bi', ...","{'analyst_tools': ['power bi', 'dax'], 'async'..."
2785,Data Engineer,Staff Software Engineer - Data Engineering (Ja...,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-05-26 13:13:28,False,False,India,year,147500.0,NaN,Zscaler,"['java', 'nosql', 'neo4j', 'redshift', 'aws', ...","{'analyst_tools': ['excel'], 'cloud': ['redshi..."
3190,Senior Data Engineer,Senior Big Data DevOps & Deployment Engineer,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-07-07 13:14:21,False,False,India,year,79200.0,NaN,ServiceNow,"['sql', 'perl', 'bash', 'groovy', 'python', 's...","{'analyst_tools': ['tableau'], 'cloud': ['azur..."
3930,Data Scientist,Lead Data Scientist,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-12-12 13:27:33,False,False,India,year,114516.0,NaN,Boeing,"['python', 'r', 'c++', 'tensorflow', 'tableau']","{'analyst_tools': ['tableau'], 'libraries': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783733,Senior Data Scientist,Senior Data Scientist,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-06-27 06:12:11,False,False,India,year,157500.0,NaN,Publicis Groupe,"['aws', 'spark', 'tableau', 'cognos', 'excel',...","{'analyst_tools': ['tableau', 'cognos', 'excel..."
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784768,Data Scientist,SR. DATA SCIENTIST,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-01-03 06:25:25,False,False,India,year,157500.0,NaN,Optiv,"['r', 'python', 'sql', 'databricks', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['dat..."
785395,Data Engineer,Senior Consultant - Tech Consulting -Azure Dat...,India,via Ai-Jobs.net,Full-time,False,India,2023-12-19 06:10:41,False,False,India,year,64800.0,NaN,EY,"['sql', 'python', 'azure', 'databricks', 'spar...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [26]:
India.groupby('job_title_short')['salary_year_avg'].agg(['median','min','max','count']).sort_values(by='median', ascending=False) # to find median min max count of salary year average of diff data jobs in India

                             median      min       max  count
job_title_short
Senior Data Scientist      149653.0  64800.0  170575.0     33
Senior Data Engineer       147500.0  35000.0  181765.0     57
Data Engineer              147500.0  43200.0  249000.0    169
Data Scientist             114008.0  43200.0  204381.0     92
Senior Data Analyst        111175.0  64800.0  177283.0     27
Data Analyst               100500.0  32400.0  650000.0     94
Machine Learning Engineer   79200.0  32500.0  267000.0     57
Software Engineer           79200.0  44418.5  200000.0     45
Business Analyst            64800.0  43200.0  142025.0      8